# src/OC/PlatformBundle/Resources/config/routing.yml
hello_the_world:
    path:   /hello
    defaults:   { _controller: OCPlatformBundle:Advert:index }
byebye:
    path: /bye
    defaults:   { _controller: OCPlatformBundle:Advert:byebye }
oc_platform_home:
    path: /
    defaults: { _controller: OCPlatformBundle:Advert:index}
oc_platform_view:
    path: /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view}
oc_platform_view_slug:
    path: /{year}/{slug}.{format}
    defaults: 
        {_controller: OCPlatformBundle:Advert:viewSlug, format: html}
    requirements:
        year: \d{4}
        format: html|xml